### ISSUE TITLE
What file types are supported

### ISSUE THREAD

**Issue by suntong** [mh-cbon/emd#1]
In README.e.md, the **API example** section, there is:

`{{file "main_example.go"}}
`

So how is this file type determined? 
What other file types are supported? 

BTW, I replied your announcement message in the go-nuts mlist. please check it out. 

thanks

**Comment by mh-cbon** [comment]
> So how is this file type determined?

Based on the extension.

>  What other file types are supported?

Any MD printable file, exclude all binary file.

It is just about displaying file content within backquotes \`\`\`+[lang]

**Comment by suntong** [comment]
Thanks. 

I was worrying that determining file type based on the extension might not be good enough, (e.g., Perl & Python scripts don't use Perl & Python as extensions), but as you hinted, they are fine. 

Ref: http://tinker.kotaweaver.com/blog/?p=152

**Comment by mh-cbon** [comment]
great link.

Maybe the file func should take an extra argument to tell about the desired colorizer, 
in addition to the current simple ext detection.

I keep it open for later.

**Comment by suntong** [comment]
Yeah, that'd be super, especially for cases like, 

- Python2 and Python3
- PHP with HTML (`html+php`)

etc.
