### ISSUE TITLE
Extra spacing after GoDoc badge

### ISSUE THREAD

**Issue by suntong** [mh-cbon/emd#14]
There is an extra space after GoDoc badge, please take a look at https://github.com/go-shaper/shaper, where the badges [should be on the same line](https://github.com/go-shaper/shaper/tree/6666e248b5d4517b01fa458346ccce3aac4ce186), instead of two. I think that's because the wrong assumption that GoDoc badge is the last, whereas in fact different people might have different opinions. 

Moreover, I personally think none of the template should have the extra spaces. I.e., I'd prefer my source `README.e.md` has an arrangement like this:

```
{{template "badge/travis" .}}
{{template "badge/appveyor" .}}
{{template "badge/godoc" .}}
{{template "badge/goreport" .}}
```

I.e., I, the doc owner, add where the CR-LF is, but not the tool enforcing anything. 

Please consider.

**Comment by mh-cbon** [comment]
please do a pr
