### ISSUE TITLE
Use real path

### ISSUE THREAD

**Issue by suntong** [mh-cbon/emd#15]
When figuring out site for badges, (e.g. https://godoc.org/**github.com**/suntong/cascadia), `emd` apparently is using `pwd`. 

However, my normal `pwd` doesn't contains the strings like **github.com** because I use symlinks to made my `pwd` as short as possible, in order to avoid long path on my command prompt. So my 

/long/path/under/mount/to/where/go/src/github.com/suntong/cascadia

only appears as `~/l/gh/suntong/cascadia` as my normal `pwd`. In this case `emd` will fail to guess the site for badges. The solution is obviously to use real path instead of `pwd`, which can be obtained by `readlink -f` under Linux:

```
SYNOPSIS
       readlink [OPTION]... FILE...

DESCRIPTION
       Print value of a symbolic link or canonical file name

       -f, --canonicalize
              canonicalize  by  following  every symlink in every component of
              the given name recursively; all  but  the  last  component  must
              exist

```

Please consider.

**Comment by mh-cbon** [comment]
OK, i ll take a PR if you give me one. But can you check first if we can use os.Stats ? Oherwise, that should be segregated to mac/bsd/linux systems only (i mean a windows user should not call to readlink, right ?) (about plan9 i have **** no idea how it works)

**Comment by suntong** [comment]
Ha, you got me. 

OK, I'll look for a Go implementation instead, then do a PR.

**Comment by suntong** [comment]
Found it, use `filepath.EvalSymlinks` pls. 

Ref: https://github.com/suntong/lang/blob/master/lang/Go/src/sys/EvalSymlinks.go#L45-L52

**Comment by mh-cbon** [comment]
yes!

**Comment by suntong** [comment]
Would you try ~~to clone the https://github.com/go-cc/cc2py~~ to create a directory in some unconventional places, say /export/repo/gitwork/src/**github.com/go-cc/cc2py** and try out `emd` there please?

For the following:

```
# {{.Name}}

{{render "license/shields" . "License" "MIT"}}
{{template "badge/godoc" .}}
{{template "badge/goreport" .}}
{{template "badge/travis" .}}
```

I got:

```
# src

[<nil>](<nil>)
[![GoDoc](https://godoc.org/github.com/gitwork/src?status.svg)](http://godoc.org/github.com/gitwork/src)
[![Go Report Card](https://goreportcard.com/badge/github.com/gitwork/src)](https://goreportcard.com/report/github.com/gitwork/src)
[![travis Status](https://travis-ci.org//gitwork/src.svg?branch=master)](https://travis-ci.org//gitwork/src)
```

which is all wrong. 

My `emd` is latest from `go get`:

```
$ emd -version
emd - 0.0.0
```

The fix  adea054 looks good, and my `go run EvalSymlinks.go /export/repo/gitwork/src/github.com/go-cc/cc2py` produces desired output as well. 

What went wrong? Thx.

**Comment by mh-cbon** [comment]
for the license, it s not good syntax, you can use prelude data like,
https://raw.githubusercontent.com/mh-cbon/emd/master/README.e.md

Or use the render func to name the values, i think,
`{{render "license/shields" . "LicenseFile" "License" "License" "MIT" "LicenseColor" "yellow"}}`


Did you generate it from a GOPATH, or outside of it ?

/export/repo/gitwork/src/github.com/go-cc/cc2py 

Is this your GOPATH ? 

/export/repo/gitwork

Anyways, i think its time to implement serious testing!

**Comment by suntong** [comment]
No my own code is outside GOPATH, byt smylinked into it. 
I.e., my GOPATH is entirely different than `/export/repo/gitwork/src/github.com/go-cc/cc2py`

**Comment by mh-cbon** [comment]
thanks

**Comment by mh-cbon** [comment]
I missread somethign,

the project is at 
/export/repo/gitwork/src/github.com/go-cc/cc2py****

let s say the gopath is actually
/home/gow/src/github.com/go-cc/cc2py****

I ll add test for both WD, 
let s see.

**Comment by mh-cbon** [comment]
if you can give it a try and a feedback that d be great! thanks!

**Comment by suntong** [comment]
Oh, I got:

2017/05/05 20:57:06 command "gen" failed: Invalid working directory "/export/my-mount/my-caches/repo/gitwork/src/github.com/go-cc/cc2py"

Is it because of [this line](https://github.com/mh-cbon/emd/commit/bee5a74d0a0d6cdc9b2c96e14c4921cc38a37d02#diff-7ddfb3e035b42cd70649cc33393fe32cR117)?

Again, my own code is outside GOPATH.

**Comment by suntong** [comment]
There has been a time, when I cd into my real path and do emd, and it worked. I guess you've somehow changed more than just get the real path for `pwd`.

**Comment by mh-cbon** [comment]
the problem is path like this 
`/export/my-mount/my-caches/repo/gitwork/src/github.com/go-cc/cc2py/cmd`
As the path is not gopath contained, 
the algo used to understand the path by the right, leading to wrong results with sub folders.
Now it always tries to interpret it from the left, starting by checking it is gopath contained.

A solution i see is to add a parameter to feed that value and not try to guess it.
Something like `emd -p github.com/go-cc/cc2py`

**Comment by mh-cbon** [comment]
Try this commit if you have a minute please,

https://github.com/mh-cbon/emd/commit/3e93444792c64671a98f8c0c6038136864790e30

Should put you back on track

**Comment by suntong** [comment]
Yep, exactly. I was thinking to propose to judge by the sites previously, glad that you think the same way as well. 

Do you think using regexp is a better option? To judge by the sites with something like `/\w+\.[com|org|net]/`? Because although I use github.com most of the time, I do have other git repos like

- bitbucket.org
- git.code.sf.net

and other .net repos from China as well.

**Comment by mh-cbon** [comment]
cool!

yep i thought about as well, not sure why i did not retained it.

The regexp might be more suitable with `/^src\/[^/]+[.][com|org|net]/.+` ?

the src prefix would act as anchor.

then strip the prefix src/.

Also make sure it has some trailing.

I m not sure. For instance i want to release to next version. So i suggest to to open a new ticket for future update (when its pressing :/)

**Comment by suntong** [comment]
The travis url generated is https://travis-ci.org//go-cc/cc2py, which should be OK but it always give blank a page. It is only  https://travis-ci.org/go-cc/cc2py that gives the correct result. I didn't believe until I tried them.

**Comment by mh-cbon** [comment]
erf. Just released
