### ISSUE TITLE
Using regexp to find the git site

### ISSUE THREAD

**Issue by suntong** [mh-cbon/emd#17]
Logging a new one [from here](https://github.com/mh-cbon/emd/issues/15#issuecomment-299640826).

**Comment by mh-cbon** [comment]
do you have some urls examples i can work with ? Looks like there might a new release sooner that i wanted :s

**Comment by suntong** [comment]
- https://bitbucket.org/xpt/lang
- https://code.csdn.net/fxsjy/goseg/

and git.code.sf.net just doesn't have a web interface instead of it's normal sf.net one.

**Comment by mh-cbon** [comment]
that should be fixed in latest
