### ISSUE TITLE
Using template data

### ISSUE THREAD

**Issue by suntong** [mh-cbon/emd#19]
Any way to use template data not standalone but within other strings? 

Say I have a prelude of:

```
---
myfile: some_file.txt
---
```

How can I use this in the string of, say, `shell` command? 

I.e., 

    $ {{shell "sed 'some command' < .myfile"}}

Also, how to override the definition of `myfile` from `emd` command line? 

Thx!

**Comment by mh-cbon** [comment]
To concatenate strings you can use `concat(x ...string) string` func.
https://github.com/mh-cbon/emd#markdown-functions

$ {{ shell (concat "sed 'some command' < " .myfile) }}

Unfortunately i m afraid we reached the limits of the template engine in its current form.
Its syntax capabilities are limited, and further complex structure, by experience,
does not necessarily leads to better clarity.
https://github.com/mh-cbon/emd/blob/master/std/emd.go#L353
: x

I need to check about that, `Also, how to override the definition of myfile from emd command line?`, i though that d be working out of the box :x

**Comment by suntong** [comment]
Good enough for me, :) Thx. :+1:
