### ISSUE TITLE
codeship.com badges

### ISSUE THREAD

**Issue by suntong** [mh-cbon/emd#2]
Taken from my reply of your announcement message in the go-nuts mlist:

Is it possible to support the codeship.com badges? They are ID based. e.g., 

https://codeship.com/projects/147070
https://codeship.com/projects/135255

for

https://github.com/go-shaper/shaper
https://github.com/go-easygen/easygen

etc.

**Comment by mh-cbon** [comment]
That commit should do the job,

https://github.com/mh-cbon/emd/commit/f33a8c025805f8e317826e3644f72402ba6dfe5a

check also,

https://github.com/mh-cbon/emd#templates

Let me know!

**Comment by suntong** [comment]
Thanks. 

> Add it with --data '{"CsUUID": "xxxxxx"}'

where to add it please? 

Is it possible to extend the API to something like this?

`{{template "badge/codeship" . "CsUUIDxxxxxx"}}
`

Also, could you add a codeship.com badge to the emd project as an example please? Thx.

**Comment by mh-cbon** [comment]
Step by step,

in my src README.e.md, i added, `{{template "badge/codeship" .}}`
Then i generate the README.md file with `$ emd gen`.

The result is,
`[![codeship Status](https://codeship.com/projects/<no value>/status?branch=master)](https://codeship.com/<no value>)`

To fix the ` <no value>`, run it like  `$ emd gen --data='{"CsUUID":"xxxx"}'`,

The result beome,
`[![codeship Status](https://codeship.com/projects/xxxx/status?branch=master)](https://codeship.com/xxxx)`

works for you ?

**Comment by suntong** [comment]
Hmm... 

How does `{{cli "emd" "gen" "-help"}}` generate the README.md file? Two steps as above or just one? 

If `{{cli "emd" "gen" "-help"}}`, can do it in just one step, is it possible to extend the API to something like this

`{{template "badge/codeship" . "CsUUIDxxxxxx"}}
`

So that it can be finished in just one step as well please?

**Comment by mh-cbon** [comment]
Agreed,

the syntax should be `{{template "badge/codeship" . "CsUUID" "xxxxxx"}}`

It needs a new func to render the template which handles those extra arguments.

**Comment by suntong** [comment]
Trying out your new `emd` version for the first time... 

and realized that the codeship.com badges need yet another extra argument. 

Here is what's my md before:

       [ ![Codeship Status for go-shaper/shaper](https://codeship.com/projects/04245480-e7ff-0133-dc96-46bb3aa6b241/status?branch=master)](https://codeship.com/projects/147070)

Here is what generated:

      [![codeship Status](https://codeship.com/projects/04245480-e7ff-0133-dc96-46bb3aa6b241/status?branch=master)](https://codeship.com/04245480-e7ff-0133-dc96-46bb3aa6b241)

and https://codeship.com/04245480-e7ff-0133-dc96-46bb3aa6b241 will give 404.

**Comment by mh-cbon** [comment]
please do a pr

**Comment by suntong** [comment]
Alright. 

OK to do one pr for all three?

**Comment by mh-cbon** [comment]
do it as you feel i won t be picky. But if you can make three commits that s better! The changelog will be generated automatically.

thanks :)

**Comment by suntong** [comment]
Alright, will do. three commits that's for sure.

**Comment by mh-cbon** [comment]
i ll handle it while working on some new stuff.

**Comment by suntong** [comment]
> The changelog will be generated automatically.

How do you do that? It looks fantastic.

**Comment by mh-cbon** [comment]
does this helps ?

https://github.com/mh-cbon/go-github-release#maintaining-a-changelog

thanks for reports, i ll check that.
