### ISSUE TITLE
Fail on all README that contains go templates

### ISSUE THREAD

**Issue by suntong** [mh-cbon/emd#22]
I was trying to convert README.md from
https://github.com/go-easygen/easygen
to README.e.md, then I realized that if any README contains go templates, it will fail for `emd`. 

Is there any workaround for it? Thx.

**Comment by mh-cbon** [comment]
Hi @suntong , please check the echo func https://github.com/mh-cbon/emd#markdown-functions

**Comment by suntong** [comment]
Hmm... nah, then my doc would be full of code instead of doc. Too much hassle to go that route for my above doc. How about the following? 

Provide a func of `include` that includes file(s) without further template processing. For those that do need further template processing, use the func `import` instead.

**Comment by mh-cbon** [comment]
sorry i did not understand :x can you help ?

**Comment by suntong** [comment]
Oh, basically I'm asking whether it is possible to includes other files from the main file (think of including files in LaTex), and there can be two modes, with further template processing or without. And the "without" version is the one I'm asking for.

**Comment by mh-cbon** [comment]
`cat` func should be able to read and include the file without processing, no ?

> with further template processing

mmhhh yeah might be interesting indeed.

**Comment by suntong** [comment]
oh, gotya. 

Ah, maybe no. When I say, "without further template processing", I meant no more template processing by `emd`, but the content is still treated by markdown. Can `cat` do that?

**Comment by mh-cbon** [comment]
mh yes, for example when you do `{{cat "file" | color "go"}}`, it simply reads the file content and prints it into a triple backquote go block. does it help ?

**Comment by suntong** [comment]
No, I mean it is still need to be processed as markdown text, the same way as when it was part of main file. 

Here is a concrete example, take a look at this file,
https://raw.githubusercontent.com/go-easygen/easygen/master/README.md

- split it into three files (part1~3). 
- in the main README.md, there are only three functions, 

```
{{include part1}}
{{include part2}}
{{include part3}}
```

- the effect would be exactly the same as the original big file.

Clearer this time?

**Comment by mh-cbon** [comment]
ah yes, it s like a php include!

**Comment by suntong** [comment]
> Provide a func of **`include`** that includes file(s) _without_ further template processing. For those that do need _further_ template processing, use the func **`import`** instead.

The func of `include` is provided by `read`.
