### ISSUE TITLE
Chocolatey Package Stuck in Moderation

### ISSUE THREAD

**Issue by solvingj** [mh-cbon/emd#24]
Package Status: Reviewed, waiting for user action
Submitted Date: 5/10/2017
Reviewed: 5/10/2017

**Comment by mh-cbon** [comment]
yeah, lots of problem of moderation problem with chocolatey team.

I am not autonomous, it always go through some validation process (that i barely understand, to be truthful)

If i d have completed their request, it d be there, its blocking in the sense they require manual operations in an automatic process.
Maybe some of their requests can be handled automatically, it something to check case by case.

On long term, i d prefer a system where i am autonomous.
On short term, undecided if i ll keep support for choco, or, for simplicity, deprecate it because right now i d like to focus on other topics.

the situation arise on many software i released to them.

**Comment by solvingj** [comment]
please keep support for chocolatey, the consistent streamlined experience for windows and linux ci process pulling from package managers is really nice and important.  i want to use your toolset for several apps in the future, because it addresses so many shared concerns so effectively in it's current form.  If you need help, please feel free to email me.

**Comment by mh-cbon** [comment]
I ll keep it open to get back on it later.

**Comment by solvingj** [comment]
Hi @mh-cbon , is now later?

Here is the latest update from Chocolatey team:

```
flcdrg (reviewer) on 23 Apr 2017 23:34:47 +00:00:

(Repeating request)

Because you have included binaries in the package:

can you include a completed tools\VERIFICATION.txt and tools\LICENSE.txt files (eg. similar to that produced from choco new).
```

**Comment by mh-cbon** [comment]
Verification.txt
```
﻿
Note: Include this file if including binaries you have the right to distribute. 
Otherwise delete. this file.

===DELETE ABOVE THIS LINE AND THIS LINE===

VERIFICATION
Verification is intended to assist the Chocolatey moderators and community
in verifying that this package's contents are trustworthy.
 
<Include details of how to verify checksum contents>
```

Im not sure what is required here. the checksum is already provided at
https://github.com/mh-cbon/go-msi/blob/master/templates/choco/chocolateyInstall.ps1#L7

I double checked the sums they are correct (checksum.exe uses uppercase, where this implementation uses lowercase https://github.com/mh-cbon/go-msi/blob/master/util/index.go#L46). 

So i guess they only need the file to exist...........

______________________

About license file it is more tricky...

LICENSE.txt
```
﻿
Note: Include this file if including binaries you have the right to distribute. 
Otherwise delete. this file.

===DELETE ABOVE THIS LINE AND THIS LINE===

From: <insert applicable license url here>

LICENSE

<Insert License Here>
```

They want to have a copy of the license text in the file, which makes sense, but if my license url is (https://github.com/mh-cbon/go-msi/blob/master/wix.json#L44), the content will contain lots of garbage.

On the other hand if i check at https://choosealicense.com/ there is not one dictionary of license i can rely on to download the text and copy it into the file.

__________________

unless a good idea, i guess i d better be stupid and put the files and their content as desired and let see if that effort was worthy.

**Comment by mh-cbon** [comment]
see https://github.com/mh-cbon/go-msi/commit/1d5165326c40e363fe864ca0417293829e6f1c88

**Comment by mh-cbon** [comment]
it is still in moderation status. I realized it never passed the moderation, like never. Not sure what s the problem.

Last message i received is

> chocolatey-ops (reviewer) on 24 Aug 2017 21:18:45 +00:00:
> 
> emd has passed automated testing.
> This is not the only check that is performed so check the package page to ensure a 'Ready' status.
> Please visit https://gist.github.com/fb7540d819d5d01f38dcea888c498289 for details.
> This is an FYI only. There is no action you need to take. 

https://gist.github.com/choco-bot/fb7540d819d5d01f38dcea888c498289

**Comment by mh-cbon** [comment]
ok never mind, i found out, it was in the previous release. 
Should be fine as soon as their moderators jumps in.

> Because  you have included binaries in the package:
> please include a complete tools\VERIFICATION.txt and tools\LICENSE.txt files (eg. similar to that produced from choco new)

and they are added since recently.

**Comment by solvingj** [comment]
no such luck. still in moderation i think.
