### ISSUE TITLE
Modules must be semantically versioned according to semver

### ISSUE THREAD

**Issue by suntong** [mh-cbon/emd#32]
Hi @mh-cbon, 

I like your `emd` so much that I am packaging it as a Debian package. However, I'm having problem to have my script download the latest release. Would you click on the following url and see what you get please? 

https://github.com/mh-cbon/emd/archive/1.0.1.tar.gz

Do you get a `404: Not Found` as well?

**Comment by suntong** [comment]
BTW, if you pack a new release, as per the Debian/Go naming convention, please tag it with prefix char "v", i.e., `v1.0.1` as opposed to just `1.0.1`, because

`WARNING: Latest tag "1.0.1" is not a valid SemVer version`

**Comment by suntong** [comment]
Oh, another thing, I don't know what version of your release file will show, but if I build from source, I'm getting:

```
$ emd
emd - 0.0.0

Usage
. . . 
```

I.e., it says v0.0.0 instead of v1.0.1

**Comment by suntong** [comment]
First comment was 8 days ago

**Comment by mh-cbon** [comment]
those links looks ok https://github.com/mh-cbon/emd/releases UI has changed since microsoft bought github.

if you build the source, version will always be 0.0.0 unless you rewrite the VERSION variable on compile.
see 

https://github.com/mh-cbon/emd/blob/master/.travis.yml#L43

https://github.com/mh-cbon/emd/blob/master/appveyor.yml#L59

I guess we could have have v....

**Comment by suntong** [comment]
Thanks for the reply @mh-cbon 

> those links looks ok. . . UI has changed since microsoft bought github

Yeah, I'm able to access it myself as well. Can't remember what was the problem now. Anyway,

> BTW, if you pack a new release, as per the Debian/Go naming convention, please tag it with prefix char "v", i.e., `v1.0.1` as opposed to just `1.0.1`, because
> 
> `WARNING: Latest tag "1.0.1" is not a valid SemVer version`

Would you tag your currnet `1.0.1` version with another tag `v1.0.1` please? As I'm having a hard time packaging it without the "v", due to that it _"is not a valid SemVer version"_:

```
2020/07/16 21:37:43 Downloading "github.com/mh-cbon/emd/..."
2020/07/16 21:37:57 Determining upstream version number
2020/07/16 21:37:57 Found latest tag "1.0.1"
2020/07/16 21:37:57 WARNING: Latest tag "1.0.1" is not a valid SemVer version
2020/07/16 21:37:57 Latest tag "1.0.1" matches master
2020/07/16 21:37:57 Package version is "1.0.1"
2020/07/16 21:37:57 Determining dependencies
2020/07/16 21:37:59 Downloading https://github.com/mh-cbon/emd/archive/v1.0.1.tar.gz
2020/07/16 21:38:00 Could not create a tarball of the upstream source: 404 Not Found
```

I tried again just now. and failed again. 

Please tag your currnet version as `v1.0.1` as well. thx!

**Comment by suntong** [comment]
So the problem is cause by that _"Modules **must** be semantically versioned according to [semver](https://semver.org/)"_. According to [go/wiki](https://github.com/golang/go/wiki/Modules#modules) --

> Modules  **must** be semantically versioned according to [semver](https://semver.org/), usually in the form `v(major).(minor).(patch)`, such as `v0.1.0`, `v1.2.3`, or `v1.5.0-rc.1`.  **The leading `v` is required**. If using Git, [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) released commits with their versions. Public and private module repositories and proxies are becoming available (see FAQ [below](https://github.com/golang/go/wiki/Modules#are-there-always-on-module-repositories-and-enterprise-proxies)).

**Comment by mh-cbon** [comment]
what is this command output ? I dont recognize.

**Comment by mh-cbon** [comment]
their you have the tag sorry for the delay.

**Comment by suntong** [comment]
> what is this command output ?

That comes from the command to build Debian package from go source -- `dh-make-golang`

> their you have the tag

Thanks!
