### ISSUE TITLE
Usage cli support piping?

### ISSUE THREAD

**Issue by suntong** [mh-cbon/emd#5]
Does the `{{cli ... }}` under Usage section support piping? Like all those in https://github.com/suntong/cascadia, like 

    echo '<input type="radio" name="Sex" value="F" />' | tee /tmp/cascadia.xml | cascadia -i -o -c 'input[name=Sex][value=M]'

etc? Thx.

**Comment by mh-cbon** [comment]
I don t think so, https://github.com/mh-cbon/emd/blob/master/std/emd.go#L60

That d need to do a shell exec like this https://github.com/mh-cbon/gump/blob/master/stringexec/index.go#L76

I m not very happy to change cli to behave like this as it is not compatible everywhere.
I d prefer to segregate it into a new shell command.

Also that d be easier to write as you would not have to split their args, on the other hand, i suspect such command will need quiet a lot of escaping if we d do `{{shelll "...."}}`, Not so great

**Comment by suntong** [comment]
Yeah, that's a challenge.

**Comment by mh-cbon** [comment]
hi,

as i told you i m not satisfied to do manual escaping on those commands,
```
{{shell "echo '<input type=\"radio\" name="Sex" value=\"F\" />' | tee /tmp/cascadia.xml | cascadia -i -o -c 'input[name=Sex][value=M]'"}}
```

So i m thinking to add a prelude to the md file to define data, something like yaml, or simple handmade parsing,

```
key: <value>
key1: echo '<input type="radio" name="Sex" value="F" />' | tee /tmp/cascadia.xml | cascadia -i -o -c 'input[name=Sex][value=M]'
----
content of the readme goes here
{{.key}}
{{.key1}}
```

**Comment by suntong** [comment]
Yeah, agree, I also think that the prelude or something is better than escaping (manually!)

**Comment by suntong** [comment]
Oh, use YAML, although it might be heave, it looks good in GH. For e.g., the following:

```
---
title: "Easygen - Easy to use universal code/text generator"
date: "2016-01-01T22:13:12-05:00"
categories: ["Tech"]
tags: ["go","programming","easygen","CLI"]
---
```

looks really good in GH:
https://github.com/suntong/blogs/blob/master/content/post/EasygenIntro.md

**Comment by mh-cbon** [comment]
awesome  @suntong

**Comment by mh-cbon** [comment]
please close it if/when ok

**Comment by suntong** [comment]
Sure, 

~~but currently pending on the issue reported in https://github.com/mh-cbon/emd/commit/e163773171bd707cd0916d6c5dc87e35a2c98199~~  
Hmm..., no that's caused by the "TOC level >=4 " assumption. 

However, this apparently more challenging than we thought. Here is my attempt:

```
---
SingleSel1: echo '<input type="radio" name="Sex" value="F" />' | tee /tmp/cascadia.xml | cascadia -i -o -c 'input[name=Sex][value=M]'
---

{{shell {.SingleSel1} | color "sh"}}
```

This will however give 

    panic: command "gen" failed: Generator failed: template: :39: unexpected "{" in operand

So, now we step back and rethink what we should be doing:

- User define the string exactly as what would be shown in README. 
- `emd gen` will generate that exact string in README, as the document
- `emd gen` will also need to pass the properly escaped string to shell so that it can get the correct shell output. 

That's what we'll be doing.

**Comment by suntong** [comment]
Moreover, 

For this:

    $ {{shell "cascadia -i /tmp/cascadia.xml -o -c 'input[name=Sex][value=F]'" | color "sh"}}

The generated code is, 

```
    $ cascadia -i /tmp/cascadia.xml -o -c 'input[name=Sex][value=F]'
    ```sh
    1 elements for 'input[name=Sex][value=F]':
    <input type="radio" name="Sex" value="F"/>
    ```
```

however, since it is shell command and output, I'd more prefer that the output is:

```
    ```sh
    $ cascadia -i /tmp/cascadia.xml -o -c 'input[name=Sex][value=F]'
    1 elements for 'input[name=Sex][value=F]':
    <input type="radio" name="Sex" value="F"/>
    ```
```

So that the _shell command line_ get proper highlighted _as well_. 

If people prefer to add more before the shell output, they may do so by adding them before the `{{shell}}` macro themselves. Again, this is about giving the doc owner the control.

**Comment by mh-cbon** [comment]
yeah i agree, but practically speaking how you implement that ?

**Comment by suntong** [comment]
> but practically speaking how you implement that ?

Did you mean 

- properly escaped string to shell so that it can get the correct shell output
- or, put the shell command line inside `sh` block

?

**Comment by mh-cbon** [comment]
a bit of both of them, because the point of this change is to give back control to the owner, but here i should do the contrary. I really dont see how to.

However i know how to do like you wanted,

    ```sh
    $ {{shell "cascadia -i /tmp/cascadia.xml -o -c 'input[name=Sex][value=F]'"}}
    $ {{shell "cascadia -i /tmp/cascadia.xml -o -c 'input[name=Sex][value=F]'"}}
    $ {{shell "cascadia -i /tmp/cascadia.xml -o -c 'input[name=Sex][value=F]'"}}
    ```

**Comment by mh-cbon** [comment]
but you need to unconfigure the prelude into the options! so, if d want a prelude on exec somewhere else, you add it there.

**Comment by mh-cbon** [comment]
i mean, like this

`#### $ {{exec "emd" "-help" | color "sh"}}`

**Comment by suntong** [comment]
Here is my thought, 

For `{{shell "cascadia -i /tmp/cascadia.xml -o -c 'input[name=Sex][value=F]'" | color "sh"}}`, the output will be:

```
    ```sh
    $ cascadia -i /tmp/cascadia.xml -o -c 'input[name=Sex][value=F]'
    1 elements for 'input[name=Sex][value=F]':
    <input type="radio" name="Sex" value="F"/>
    ```
```

I.e., putting the shell command line inside `sh` block, with an extra `"$ "` that can be override by prelude. 

For 

    #### $ {{exec "emd" "-help" | color "sh"}}

Just let the doc owner do, 

    #### $ emd -help
    {{exec "emd" "-help" | color "sh"}}

I.e., the doc owners have full control of what's outside the `sh` block, while `emd` has full control of what's inside the `sh` block. 

As for _properly escaped string to shell so that it can get the correct shell output_, invoke the shell at go code level, while passing the already properly escaped string to it as parameter. To properly escape a complicated string in Go, that I'm not quite sure (and I can look into that), but when doing it at shell command line, it's simply as quoting the whole thing in single quoting "`'`", then for the whole string itself, replace every single quoting "`'`" with "`'\''`".

**Comment by suntong** [comment]
You can test it out like this:

```
---
SingleSel1: echo '<input type="radio" name="Sex" value="F" />'"<date val='`date`' />" | tee /tmp/cascadia.xml | cat
---

{{shell {.SingleSel1} | color "sh"}}
```

**Comment by suntong** [comment]
Hmm, actually, 

I like your idea better, I.e., 

    ```sh
    $ {{shell "cascadia -i /tmp/cascadia.xml -o -c 'input[name=Sex][value=F]'"}}

    $ {{shell "something else"}}

    $ {{shell "something more"}}
    ```

And `{{exec}}` can remain the same, if you want. 

So, only chipping in my two cents here. 
All up to you, but I do love your above idea.

**Comment by mh-cbon** [comment]
great :) are we good to close ?

> As for properly escaped string to shell so that it can get the correct shell output, invoke the shell at go code level, while passing the already properly escaped string to it as parameter. To properly escape a complicated string in Go, that I'm not quite sure (and I can look into that), but when doing it at shell command line, it's simply as quoting the whole thing in single quoting "'", then for the whole string itself, replace every single quoting "'" with "'\''".

oh sorry. I was only rhetorical, my bad really sorry. In fact the command is wrote into a file as is, and the file is invoked on the shell, so there is no need to escape.

**Comment by suntong** [comment]
Hmm..., not yet:

    ---
    ShellTest: echo '<input type="radio" name="Sex" value="F" />'"<date val='`date`' />" | tee /tmp/cascadia.xml | cat
    ---

    ```sh
    {{shell {.ShellTest}}}
    ```

I'll get:

```
panic: command "gen" failed: Generator failed: template: :3: unexpected "{" in operand

goroutine 1 [running]:
panic(0x583d20, 0xc420073150)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
        /export/repo/go-arch/src/github.com/mh-cbon/emd/main.go:28 +0xa4
```

Can you try and see what you get pls?

BTW, use`uname` if you want to put above into test case:

```
$ uname 
Linux

```

**Comment by mh-cbon** [comment]
but why did you put an open brace ? `{{shell .ShellTest}}`

**Comment by suntong** [comment]
Duh!

**Comment by suntong** [comment]
Wait, 

```
---
.SingleSel2: cascadia -i /tmp/cascadia.xml -o -c 'input[name=Sex][value=F]'
---

```sh
$ {{shell .SingleSel2}}
```
```

will get 

```
panic: command "gen" failed: Generator failed: template: :46:10: executing "" at <.SingleSel2>: invalid value; expected string

goroutine 1 [running]:
panic(0x583d20, 0xc4201f7730)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
        /export/repo/go-arch/src/github.com/mh-cbon/emd/main.go:28 +0xa4

```
